bw_blog_category:
    resource: "@BWBlogBundle/Resources/config/routing/category.yml"
    prefix:   /category

index:
    path:     /
    defaults: { _controller: BWBlogBundle:Default:index }

bw_blog_post:
    resource: "@BWBlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

test_redirect:
    path: /redirect
    defaults:
        _controller: BWBlogBundle:Default:redirect
