bw_blog_post:
    resource: "@BWBlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

bw_blog_homepage:
    path:     /hello2/{name}/{surname}
    defaults: { _controller: BWBlogBundle:Default:index }

test_redirect:
    path: /redirect
    defaults:
        _controller: BWBlogBundle:Default:redirect
